## Compiler tool 
GCC    := g++

## Subdirectories Path
SRC_DIR = Src

################################################
########### Don't edit below ###################
################################################
all: 
	$(MAKE) -C $(SRC_DIR)

clean:
	$(MAKE) -C $(SRC_DIR) clean

rebuild: clean all

run: 
	./Out/Demo

.PHONY: all clean rebuild run

	